# Generated by Django 5.2.13 on 2026-04-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='estado',
            field=models.CharField(default='En revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='referencia',
            field=models.CharField(default='TEMP', editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
